# Generated by Django 2.2 on 2019-04-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
