# Generated by Django 2.2 on 2019-04-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190427_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/publicaciones/%Y%m%d/'),
        ),
    ]
